---

number_of_links: 7

links:

    link0:

        name: "Trunk"
        parent: "world"
        alpha: 0 
        th: 0
        d: 0
        a: 1
        type: "fixed"

    link1:

        name: "Shoulder"
        parent: "Trunk"
        alpha: -1.571
        th: -1.8
        d: 0.335
        a: 0.075
        type: "revolute"

    link2:

        name: "UpperArm"
        parent: "Shoulder"
        alpha: 0
        th: -2.13
        d: 0
        a: 0.270
        type: "revolute"

    link3:

        name: "ForeArm"
        parent: "UpperArm"
        alpha: 1.571
        th: 0
        d: 0
        a: 0.090
        type: "revolute"

    link4: 

        name: "Wrist1"
        parent: "ForeArm"
        alpha: -1.0
        th: 0
        d: -0.295
        a: 0
        type: "revolute"

    link5:

        name: "Wrist2"
        parent: "Wrist1"
        alpha: 1.571
        th: 0
        d: 0
        a: 0
        type: "revolute"

    link6:

        name: "Wrist3"
        parent: "Wrist2"
        alpha: 3.14
        th: 0
        d: -0.80
        a: 0
        type: "revolute"

...

